
#type: args

train:
  epochs: 5
  batch_size: 32 
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8


diffusion:
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 10
  schedule: "cos-sin"
  is_linear: False

model:
  is_unconditional: 0
  timeemb: 64
  featureemb: 16
  target_strategy: "random"

graph:
  gcn_in: 4
  hidden: 64
  gcn_out: 64
  gcn_layers: 3
  num_stations: 108
