
#type: args

train:
  epochs: 8
  batch_size: 16
  lr: 1.5e-3
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 4 
  channels: 64
  nheads: 4
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 30
  schedule: "cos-sin"
  is_linear: False

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  num_sample_features: 64

graph:
  gcn_in: 4
  hidden: 64
  gcn_out: 64
  gcn_layers: 3
  num_stations: 108
